# Generated by Django 3.0.8 on 2020-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('dewey', models.CharField(max_length=100, verbose_name='Book Title')),
                ('accno', models.IntegerField(verbose_name='Acc. No.')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('marc_id', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(verbose_name='Payment Date')),
            ],
        ),
    ]
