# Generated by Django 3.0.8 on 2020-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200801_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100, null=True, verbose_name='Genre'),
        ),
    ]
