# Generated by Django 3.0.8 on 2020-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('dewey', models.CharField(max_length=100, null=True, verbose_name='Dewey Decimal id')),
                ('accno', models.IntegerField(verbose_name='Accession Number')),
                ('authors', models.CharField(max_length=100, null=True, verbose_name='Authors')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Subject')),
                ('genre', models.CharField(max_length=100, null=True, verbose_name='Genre')),
                ('isbn', models.IntegerField(null=True, verbose_name='ISBN Number')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='journals',
            name='editors',
            field=models.CharField(max_length=100, null=True, verbose_name='Editor in Chief'),
        ),
        migrations.AddField(
            model_name='journals',
            name='issn',
            field=models.IntegerField(null=True, verbose_name='ISSN'),
        ),
        migrations.AddField(
            model_name='journals',
            name='payment_date',
            field=models.DateTimeField(null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='journals',
            name='publisher',
            field=models.CharField(max_length=100, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='journals',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Journal Title'),
        ),
    ]
