# Generated by Django 3.0.8 on 2020-08-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0002_auto_20200801_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journals',
            new_name='Journal',
        ),
    ]
