# Generated by Django 2.2.4 on 2020-08-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('dewey', models.CharField(max_length=100, null=True, verbose_name='Dewey Decimal id')),
                ('authors', models.CharField(max_length=100, null=True, verbose_name='Authors')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Subject')),
                ('genre', models.CharField(max_length=100, null=True, verbose_name='Genre')),
                ('isbn', models.CharField(max_length=13, null=True, verbose_name='ISBN Number')),
                ('description', models.CharField(max_length=10000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Journal Title')),
                ('publisher', models.CharField(max_length=100, null=True, verbose_name='Publisher')),
                ('editors', models.CharField(max_length=100, null=True, verbose_name='Editor in Chief')),
                ('issn', models.CharField(max_length=13, null=True, verbose_name='ISSN')),
                ('payment_date', models.DateTimeField(null=True, verbose_name='Payment Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Journals',
        ),
    ]
