# Generated by Django 2.2.4 on 2020-08-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0002_auto_20200802_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='issn',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='publisher',
        ),
        migrations.AddField(
            model_name='journal',
            name='Book_Series_Title',
            field=models.CharField(max_length=100, null=True, verbose_name='Book Series Title'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Content_Type',
            field=models.CharField(max_length=100, null=True, verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Item_DOI',
            field=models.CharField(max_length=100, null=True, verbose_name='Item Date of Issue'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Journal_Issue',
            field=models.CharField(max_length=100, null=True, verbose_name='Journal  Issue'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Journal_Volume',
            field=models.CharField(max_length=100, null=True, verbose_name='Journal  Volume'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Publication_Year',
            field=models.CharField(max_length=100, null=True, verbose_name='Publication Year'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Publisher_Title',
            field=models.CharField(max_length=100, null=True, verbose_name='Publisher Title'),
        ),
        migrations.AddField(
            model_name='journal',
            name='URL',
            field=models.CharField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
    ]
