# Generated by Django 2.2.4 on 2020-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0003_auto_20200802_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
