# Generated by Django 2.2.4 on 2020-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0004_auto_20200802_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
