# Generated by Django 2.2.4 on 2020-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0005_auto_20200802_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='id',
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False, verbose_name='Journal Title'),
            preserve_default=False,
        ),
    ]
