# Generated by Django 2.2.4 on 2020-08-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0006_auto_20200802_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='Publisher_Title',
        ),
        migrations.AddField(
            model_name='journal',
            name='Publication_Title',
            field=models.CharField(max_length=100, null=True, verbose_name='Publication Title'),
        ),
    ]
