# Generated by Django 2.2.4 on 2020-08-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0007_auto_20200802_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='dewey',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=1000, null=True, verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=1000, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='gbooks_link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Gbooks link'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=1000, null=True, verbose_name='Image Link'),
        ),
        migrations.AddField(
            model_name='book',
            name='info_link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Info Link'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.CharField(max_length=1000, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='volume_link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Volume link'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=6000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Book ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=1000, null=True, verbose_name='Book Title'),
        ),
    ]
