# Generated by Django 2.2.4 on 2020-08-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0008_auto_20200802_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, null=True, verbose_name='ISBN Number')),
                ('accno', models.CharField(max_length=64, null=True, verbose_name='Accession Number')),
                ('issue_date', models.CharField(max_length=64, null=True, verbose_name='Issue Date')),
                ('return_date', models.CharField(max_length=64, null=True, verbose_name='Return Date')),
            ],
        ),
    ]
