# Generated by Django 2.2.4 on 2020-08-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0010_auto_20200802_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='isbn',
            field=models.CharField(default='NULL', max_length=13, primary_key=True, serialize=False, verbose_name='ISBN Number'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='id',
        ),
    ]
