# Generated by Django 2.2.4 on 2020-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0011_auto_20200802_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='isbn',
            field=models.CharField(max_length=13, null=True, verbose_name='ISBN Number'),
        ),
    ]
