# Generated by Django 3.0.8 on 2020-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmate_admin', '0012_auto_20200803_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=6000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='gbooks_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Gbooks link'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='book',
            name='info_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Info Link'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN Number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Book Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Volume link'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='accno',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Accession Number'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN Number'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='return_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Book_Series_Title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Series Title'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Content_Type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Item_DOI',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Date of Issue'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Journal_Issue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Journal  Issue'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Journal_Volume',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Journal  Volume'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Publication_Title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Publication Title'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Publication_Year',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Publication Year'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='URL',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
    ]
